{{- range $container := .Values.containers }}
{{- range $port := $container.ports }}
---
apiVersion: traefik.io/v1alpha1
{{- if eq $port.protocol "http" }}
kind: IngressRoute
{{- else }}
kind: IngressRouteTCP
{{- end }}
metadata:
  name: {{ include "c.join" (list $.Release.Name $container.name $port.domain) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    "kube-ctf.io/instance": {{ include "c.join" (list $.Release.Name $container.name) }}
    {{- range $key, $value := $.Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  routes:
    {{- $match := (ternary "Host" "HostSNI" (eq $port.protocol "http")) }}
    - match: {{ $match }}(`{{ include "c.join" (list $port.domain $container.name $.Release.Name) }}.{{ $.Values.global.baseDomain }}`)
      {{- if eq $port.protocol "http" }}
      kind: Rule
      {{- end }}
      services:
        - name: {{ include "c.join" (list $.Release.Name $container.name ) }}
          port: {{ $port.number }}
  tls:
    secretName: {{ $.Values.global.tlsCert }}
{{- end }}
{{- end }}
