image:
  registry: docker.io
  repository: cyberfather/challenge-manager
  tag: latest

port: 8080
replicaCount: 1
host: challenge-manager.cfrt.dev

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  capabilities:
    drop: [ALL]
  seccompProfile:
    type: RuntimeDefault
