---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ctf-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ctf-server-role
rules:
  - apiGroups: ["", "apps", "networking.k8s.io", "traefik.io"]
    resources:
      - pods
      - replicasets
      - deployments
      - services
      - secrets
      - configmaps
      - ingresses
      - ingressroutes
      - ingressroutetcps
      - networkpolicies
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ctf-server-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ctf-server-role
subjects:
  - kind: ServiceAccount
    name: ctf-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      serviceAccountName: ctf-server
      containers:
        - name: test
          image: cyberfather/challenge-manager
          imagePullPolicy: Always
