{{- range $container := .Values.containers }}
{{- if not (empty $container.ports)}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $container.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    "kube-ctf.io/name": {{ $.Release.Name }}
    "kube-ctf.io/instance": {{ $.Release.Name }}-{{ $container.name }}
    {{- range $key, $value := $.Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  selector:
    "kube-ctf.io/name": {{ $.Release.Name }}
    "kube-ctf.io/instance": {{ $.Release.Name }}-{{ $container.name }}
    {{- range $key, $value := $.Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  ports:
    {{- range $port := $container.ports }}
    - port: {{ $port.number }}
      name: {{ $port.number | quote }}
      targetPort: {{ $port.number }}
      protocol: TCP
    {{- end }}
{{- end }}
{{- end }}
