---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ctf-server
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ctf-server-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["", "apps", "networking.k8s.io", "traefik.io"]
    resources:
      - pods
      - replicasets
      - deployments
      - services
      - secrets
      - configmaps
      - ingresses
      - ingressroutes
      - ingressroutetcps
      - networkpolicies
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ctf-server-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ctf-server-role
subjects:
  - kind: ServiceAccount
    name: ctf-server
    namespace: {{ .Release.Namespace }}
