---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    "kube-ctf.io/app": {{ .Chart.Name }}
  ports:
    - port: {{ .Values.port | default 8080 }}
      targetPort: {{ .Values.port | default 8080 }}
